apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schoolapp
  namespace: argocd
spec:
  destination:
    namespace: schoolapp
    server: 'https://kubernetes.default.svc'
  source:
    path: Section6-VaultInAGitOpsModelWithArgoCD/schoolapp-subchart
    repoURL: https://github.com/knguyen112/vault-201.git
    #'https://github.com/knguyen112/vault-201.git'
    #'https://gitlab.com/public-projects3/training/vault-201.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true