apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  rbac: {}
  repo:
    image: samgabrail/argocdvaultplugin
    mountsatoken: true
    serviceaccount: vplugin
    version: latest
  dex:
    openShiftOAuth: false
  version: latest
  ha:
    enabled: false
  tls:
    ca: {}
  image: samgabrail/argocdvaultplugin
  redis:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
  controller:
    processors: {}