# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mongodb:
  auth:
    enabled: true
    rootUser: 'schoolapp'
    rootPassword: 'mongoRootPass'

schoolapp-api:
  vault:
    status: 'disabled'
    kind: 'disabled'

# schoolapp-api:
#   vault:
#     status: 'kv_static_injector_template_file'
#     kind: 'injector'

# schoolapp-api:
#   vault:
#     status: 'kv_static_csi'
#     kind: 'csi'

# vault.status options:
# vault.status: 'kv_static' # use kv secrets engine for vault aware apps (app talks to the Vault API)
# vault.status: 'kv_static_injector_template_file' # use kv secrets engine for vault unaware apps (app uses reads secrets from a file on the file system)
# vault.status: 'kv_static_csi' # use kv secrets engine with the vault CSI provider (used for vault unaware apps)
# vault.status: '<any other value including disabled>' # use Hardcoded Values that appear in GitLab

# vault.kind options:
# vault.kind: 'injector' # uses the vault injector
# vault.kind: 'csi' # uses the vault CSI provider
# vault.kind: '<any other value including disabled>' will not rely on vault at all

