apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: schoolapp
  namespace: schoolapp
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "schoolapp"
    objects: |
      - objectName: "schoolapp-mongodb-username"
        secretPath: "internal/data/schoolapp/mongodb"
        secretKey: "schoolapp_DB_USERNAME"
      - objectName: "schoolapp-mongodb-password"
        secretPath: "internal/data/schoolapp/mongodb"
        secretKey: "schoolapp_DB_PASSWORD"

# "objectName" is an alias used within the SecretProviderClass to reference
# that specific secret. This will also be the filename containing the secret.
# "secretPath" is the path in Vault where the secret should be retrieved.
# "secretKey" is the key within the Vault secret response to extract a value from.